on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [darwin, linux, windows]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
         cache: true

      - name: Build
        run: |
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          go build -ldflags "-s -w" -o bin/ github.com/liteldev/bdsdown

      - uses: actions/upload-artifact@v4
        with:
          name: bdsdown-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ github.sha }}
          path: bin
